---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  namespace: default
  labels:
    app: fleetman-api-gateway
spec:
  type: NodePort
  selector:
    app: fleetman-api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30020
      protocol: TCP
