---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
  namespace: default
  labels:
    app: fleetman-position-tracker
spec:
  type: NodePort
  selector:
    app: fleetman-position-tracker
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30010
      protocol: TCP
