---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  namespace: default
  labels:
    app: fleetman-webapp
spec:
  type: NodePort
  selector:
    app: fleetman-webapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
